import { Injectable } from '@angular/core';
import 'rxjs/add/operator/map';


@Injectable()
export class GetForumsProvider {

  constructor() {
    //console.log('Hello GetForumsProvider Provider');
  }

  loadForums(fid){
    // https://hackforums.net/api/v1/category/{fid}
    var jsonObj;
    console.log("FID: "+fid);
    switch(fid){
      // HF Official Info
      case 2: jsonObj = JSON.parse('{"success":true,"message":"","result":{"name":"Rules,  Announcements, News, and Feedback","description":"This is where site rules and important announcements about the site are made. Please read carefully before you join. Also you can leave us feedback or ask site questions here.","type":"f","parent":1,"ficon":"rules-news-announcements.png","children":[{"fid":134,"name":"Suggestions and Ideas","description":"If you have a suggestion for HF please post it here. Note that many ideas have already been suggested so please take the time to read our stickies.","type":"f","ficon":"ideas-suggestions.png"},{"fid":162,"name":"HF News","description":"This is the HF News forum for weekly news editions. Check back here to find out about what\'s happening on Hack Forums every week. Thanks to Yin who founded this section and the HFNT, Writers who release the editions.","type":"f","ficon":"hf-news.png"},{"fid":140,"name":"Ub3r Support","description":"This is for ub3r support only.  No one but ub3r and staff have access to this section.","type":"f","ficon":"ub3r.png"}]}}');
      break;
      // Beginner Hacking
      case 4: jsonObj = JSON.parse('{"success":true,"message":"","result":{"name":"Beginner Hacking","description":"This is for the entry level hacker wishing to learn more about the art of h4(k5.","type":"f","parent":45,"ficon":"beginner-hacking.png","children":[{"fid":170,"name":"E-Whoring","description":"This common sexual manipulation social engineering technique is often used in chat rooms and IMs.  Post more about e-whores in this forum.","type":"f","ficon":"ewhore.jpg"},{"fid":287,"name":"Worms, Malware, and Viruses","description":"This section is devoted to the study, discussion, and methodology of cryptoviral software.","type":"f","ficon":"worms.png"},{"fid":322,"name":"Private Investigation Methods and Anonymity","description":"Discuss privacy and remaining anonymous in this forum. Topics include finding private information and protecting your own data privacy.","type":"f","ficon":"privacy.png"}]}}');
      break;
      case 307: jsonObj = JSON.parse('{"success":true,"message":"","result":{"name":"Advanced Hacking","description":"If you feel you\'re past the beginner stages and want to delve deeper into computer security, analysis, and internet exploits you should participate here.","type":"c","parent":45,"ficon":"glider.png","children":[{"fid":92,"name":"Botnets, IRC Bots, and Zombies","description":"Sounds like a horror movie and for some it is.  What is a botnet? Topics for botnets belong in this area.","type":"f","ficon":"botnets.png"},{"fid":126,"name":"Cryptography, Encryption, and Decryption","description":"For discussion on keys, ciphers, and algorithms often used to keep information secret.  Encryption is the art of concealing data and code.","type":"f","ficon":"cryptography.png"},{"fid":231,"name":"Pentesting and Forensics","description":"Our forum for discussions on shellcode, Metasploit, opcode, IDS, and other server level security vulnerabilities. All server security research should be here.","type":"f","ficon":"pentesting.png"},{"fid":229,"name":"Decompiling, Reverse Engineering, Disassembly, and Debugging","description":"This area is to reverse engineer software for debugging and code understanding purposes. Content would encompass binary software, debugging programs, and decompile assembled files.","type":"f","ficon":"debug.png"}]}}');
      break;
      case 10: jsonObj = JSON.parse('{"success":true,"message":"","result":{"name":"Hacking Tools and Programs","description":"Since every hacker needs tools and programs please post your favorites here. ","type":"f","parent":45,"ficon":"keylogger2.png","children":[{"fid":113,"name":"Keyloggers","description":"A keylogger can help you in many situations.  Discuss their usage, implementation or removal in this forum.","type":"f","ficon":"keylogger.png"},{"fid":114,"name":"Remote Administration Tools","description":"Otherwise known as RATS a remote admin tool can greatly advance your abilities as a hacker. Topics include creation, dispersal, and control of RATS.","type":"f","ficon":"rat.png"}]}}');
      break;
      // Open Discussion
      case 25: jsonObj = JSON.parse('{"success":true,"message":"","result":{"name":"The Lounge","description":"For great discussions on various subjects and to have some fun relaxed topics you can enter our Lounge.  Read the rules in the forums as trolling, spamming, or flaming are not allowed.","type":"f","parent":7,"ficon":"lounge.png","children":[{"fid":364,"name":"Introductions","description":"Who the heck are you?  Welcome to HF and feel free to tell us a bit more about yourself.","type":"f","ficon":"introductions.png"},{"fid":383,"name":"Meme Shit Meme","description":"What\'s the point of the internet if you can\'t troll?","type":"f","ficon":"fuckit.png"},{"fid":198,"name":"Chat Invites like Discord, Tinychat, or Skype","description":"For those looking to chat in Skype, Discord, Tinychat, Omegle, Chatroulette, Join.me and invite others into a room please use this forum.  All Lounge rules apply here too.","type":"f","ficon":"tinychat.png"}]}}');
      break;
      case 259: jsonObj = JSON.parse('{"success":true,"message":"","result":{"name":"Personal Life","description":"Our personal life topics sections are all under subforums of this category.","type":"c","parent":7,"ficon":"personal-life.png","children":[{"fid":318,"name":"Vices","description":"For all those unhealthy things you do to yourself in the name of a good time.","type":"f","ficon":"vices.png"},{"fid":370,"name":"Jackpot Warriors","description":"For discussion about gambling online and games of chance you can post here.  Post about poker, Bustabit, Primedice, sportsbook play or just exchange tips on winning.","type":"f","ficon":"jackpot.png"},{"fid":260,"name":"Education Nation","description":"For homework help, college questions, university and other educational topics post here. Get smarter in your personal life.","type":"f","ficon":"education-nation.png"},{"fid":12,"name":"Bragging Rights","description":"If you have something you want to show off..this is the place to post.  Claim your bragging rights in this area. ","type":"f","ficon":"bragging.png"},{"fid":385,"name":"Cars, Bikes, Motors and More","description":"Discuss cars, motorcycles, and other vehicles.  Topics include brags, body repairs, purchase advice, and mechanical help.","type":"f","ficon":"vehicles.png"},{"fid":262,"name":"Health Wise","description":"For the benefit of good health we have this personal life forum.  Topics include workouts, healthy eating, hygiene, mental health and even medical questions.","type":"f","ficon":"health-wise.png"},{"fid":180,"name":"Innuendo","description":"This is our forum for sexuality topics. Please act with maturity and read the rules. Topics include relationship issues and sexual encounters.","type":"f","ficon":"innuendo.png"},{"fid":261,"name":"Pet Peeve","description":"For those cuddly creatures in your personal life.  Discuss and post pics of your pets and favorite animals in our Pet Peeve forum area.","type":"f","ficon":"pet-peeve.png"},{"fid":354,"name":"Recipes for Disaster","description":"For the love of food, cooking, and eating.  Share your favorite recipes or talk about the best restaurant you\'ve visited. ","type":"f","ficon":"recipe.png"},{"fid":167,"name":"Sports World","description":"For sports discussions like football, basketball, MMA, baseball, and hockey we have this forum just for you.  Please keep all sports topics here.","type":"f","ficon":"sports.gif"},{"fid":373,"name":"Writer Tales","description":"For all types of creative writing posts such as poetry, essays, and short stories. Show us your talent.","type":"f","ficon":"writer-tales.png"}]}}');
      break;
      case 155: jsonObj = JSON.parse('{"success":true,"message":"","result":{"name":"Member Contests","description":"This is a special forum dedicated to all the contests that members run. These are not official contests so participation is at your own risk.","type":"f","parent":7,"ficon":"contests.png","children":[{"fid":187,"name":"Freebies and Giveaways ","description":"This is a redirect to the free services and giveaways subforum in marketplace.  Do not use Contests forum for freebies.","type":"f","ficon":"giveaways.png"}]}}');
      break;
      // Computing
      case 110: jsonObj = JSON.parse('{"success":true,"message":"","result":{"name":"White Hat Malware, Virus, and Rat Removal Help","description":"Wanna stop the Black Hats and Crackers?  Do you need assistance removing a RAT, virus, or malware?  Has your site been compromised?  Help others and get help here.","type":"f","parent":88,"ficon":"hat_white.png","children":[{"fid":13,"name":"Computer Protection and Security Alerts","description":"Protect yourself from computer viruses. Advisories and alerts of new security breaches will be posted here.  ","type":"f","ficon":"security-alerts.png"}]}}');
      break;
      case 87: jsonObj = JSON.parse('{"success":true,"message":"","result":{"name":"Computer Overclocking, Customizing, and Hardware","description":"If you\'re building a system, overclocking your CPU\/GPU or just want to add something custom to your puter this is the right forum to discuss.","type":"f","parent":88,"ficon":"overclock.png","children":[]}}');
      break;
      case 79: jsonObj = JSON.parse('{"success":true,"message":"","result":{"name":"Smartphone, Mobiles, Apps, and SDK","description":"To discuss any mobile computing like iOS, Android, phreaking, app development, coding, tablets, troubleshooting or anything related to mobile we ask that you post them all here.","type":"f","parent":88,"ficon":"phreak.png","children":[{"fid":192,"name":"Android Operating System","description":"For all Android OS and hardware discussions please post here. Topics include apps, devices, and even coding.","type":"f","ficon":"android.png"},{"fid":137,"name":"iOS and iDevices","description":"The Apple iPhone, iPad and iPod Touch are at the forefront of mobile technology. Discuss iPhone applications, jailbreaking, unlocking and hacking of the iOS systems.","type":"f","ficon":"iPhone.png"}]}}');
      break;
      // Programming
      case 5: jsonObj = JSON.parse('{"success":true,"message":"","result":{"name":"Coding and Programming","description":"Ruby, ASP and other programming languages not covered in the other forums should be posted here.","type":"f","parent":151,"ficon":"hacker-coding.png","children":[{"fid":161,"name":"Lua Coding","description":"A smaller lightweight language mainly used most often for game programming. Lua can be used for standalone purpose with its simple procedural syntax.","type":"f","ficon":"lua.png"},{"fid":150,"name":"Delphi","description":"This forum is setup for all Delphi programming threads. Delphi is perfect for rapid development with its integrated IDE. Its Rapid Application Development tools are key to success.","type":"f","ficon":"delphi.png"},{"fid":130,"name":"Perl Programming","description":"Perl is an old language that\'s flexible, powerful, and versatile. Even though it\'s dated from the 80\'s today it can be used for a large number of useful scripts.  The power behind Perl is undeniable. Post here for Perl help.","type":"f","ficon":"perl.png"},{"fid":300,"name":"Query Languages and DBMS","description":"For discussion on database queries, management, and sql software we have this forum. Topics include installation, optimization, and query coding of software like MySQL, Microsoft SQL Server, SQLite and PostgreSQL.","type":"f","ficon":"dbms.png"},{"fid":149,"name":"Assembly Language and Machine Code","description":"For low-level machine coding please use this section. Topics include instructions mnemonics, memory execution, and opcode.","type":"f","ficon":"assembly.png"},{"fid":288,"name":"AutoIT","description":"The freeware scripting language for automating the Windows GUI. A new crowd pleaser this programming language makes your work much easier.  Topics include syntax, functions, and code samples for AutoIT.","type":"f","ficon":"autoit.jpg"},{"fid":340,"name":"Node.JS and Server-Side Javascript","description":"For all server-side javascript coding this forum will redirect you to the Website Construction forum.  There you can discuss Node.JS and other platforms.","type":"f","ficon":"nodejs.png"}]}}');
      break;
      case 118: jsonObj = JSON.parse('{"success":true,"message":"","result":{"name":"Visual Basic and .NET Framework","description":"Tutorials and coding help for Visual Basic are here. Microsoft\'s event driven language using the COM model. Also included are the .NET Framework topics. C# topics should be here too.","type":"f","parent":151,"ficon":"visual-basic.png","children":[{"fid":208,"name":"C# Programming Language","description":"This is for C# (C-Sharp) coding projects, help, and development. C# is an excellent multiple purpose programming language by Microsoft.","type":"f","ficon":"csharp.png"}]}}');
      break;
      case 117: jsonObj = JSON.parse('{"success":true,"message":"","result":{"name":"C\/C++\/Obj-C Programming","description":"A forum for the entire family of C\/C++\/Obj-C coding. Gain help on compiling, objects, classes, and functions.","type":"f","parent":151,"ficon":"cplusplus.png","children":[]}}');
      break;
      // Graphics
      case 6: jsonObj = JSON.parse('{"success":true,"message":"","result":{"name":"Graphics","description":"Not really anything to do with hacking but shit we have to show off some skillz somewhere.  Do it here.","type":"f","parent":156,"ficon":"graphics.png","children":[{"fid":248,"name":"Graphic Resources","description":"This section is for graphic artist resources like PSD\'s, icon packs, and other such graphic designer sharable downloads. ","type":"f","ficon":"graphic-resources.png"},{"fid":148,"name":"Graphic Battles","description":"For the GFX artists that are into battles.  This forum is just for you.","type":"f","ficon":"graphic-battles.png"},{"fid":157,"name":"GFX Contests","description":"These are member and site contests for graphics. Things like Signature Of The Week and other graphic contests will be here.","type":"f","ficon":"gfx-contests.png"}]}}');
      break;
      case 133: jsonObj = JSON.parse('{"success":true,"message":"","result":{"name":"Rate My Graphic","description":"These are threads related to graphic ratings such as your signature or avatar. Please make sure to make quality posts.","type":"f","parent":156,"ficon":"ratemygraphic.png","children":[]}}');
      break;
      // Marketplace
      case 163: jsonObj = JSON.parse('{"success":true,"message":"","result":{"name":"Marketplace Discussions","description":"This is to be used for rules, policies, feedback, and general discussions about the HF Marketplace.  Please read the stickies in this section before conducting business here.","type":"f","parent":105,"ficon":"market-talk.png","children":[{"fid":186,"name":"Free Services and Giveaways","description":"This section is for free exchanges, services, or giveaways. ","type":"f","ficon":"giveaways.png"},{"fid":205,"name":"Appraisals and Pricing","description":"To request marketplace appraisals, ask for price checks,  and discuss market pricing please post threads here. ","type":"f","ficon":"price-check.png"},{"fid":111,"name":"Deal Disputes","description":"Did you have a bad deal?  Maybe you feel scammed or didn\'t get what you bargained for. Post here. HF is not responsible for any deals but this is the place to let others know.","type":"f","ficon":"scammers.png"}]}}');
      break;
      case 107: jsonObj = JSON.parse('{"success":true,"message":"","result":{"name":"Premium Sellers Section","description":"This area is only for upgraded member sales threads. ","type":"f","parent":105,"ficon":"premium-sellers.png","children":[{"fid":374,"name":"Premium Tools and Programs","description":"For the sales of actual programs and tools for use on desktop and mobile environments.","type":"f","ficon":"ptp.png"},{"fid":182,"name":"Currency Exchange","description":"This section has limitations for thread creation for Ub3r only.  Use this forum to exchange gift card, fiat, and crypto currencies.  Please use extreme caution in all trades.  ","type":"f","ficon":"exchange.png"},{"fid":299,"name":"Cryptography and Encryption Market","description":"For those offering cryptography and encryption services and software.","type":"f","ficon":"cryptography.png"}]}}');
      break;
      case 176: jsonObj = JSON.parse('{"success":true,"message":"","result":{"name":"Secondary Sellers Market","description":"This is a sellers section open to all members.  We advise extreme caution in all deals here.  Sales threads must follow the policies of HF and we expect you to read them in the help documents.","type":"f","parent":105,"ficon":"selling.png","children":[{"fid":218,"name":"Virtual Game Items","description":"Here you can sell virtual items from games such as Runescape Gold, WoW equipment, and other gaming related items.  No account trading allowed in this section.","type":"f","ficon":"virtual-items.png"},{"fid":206,"name":"Member Auctions","description":"Use this section to start an auction. This is not for off-site auction linking.  All auctions must follow strict guidelines.","type":"f","ficon":"auction_hammer.png"},{"fid":108,"name":"Traders Topics","description":"If you want to make a trade or exchange with a member we want it posted here.  A trade example would be HF l33t upgrade in exchange for posts at a site.","type":"f","ficon":"trades.png"}]}}');
      break;
      // Making Money
      case 120: jsonObj = JSON.parse('{"success":true,"message":"","result":{"name":"Monetizing Techniques","description":"If you\'re looking for methods to make more money online this is your forum. We ask that if you have great ideas or a system to monetize please share it. Please read the rules for this forum.","type":"f","parent":241,"ficon":"monetizing.png","children":[{"fid":369,"name":"Business Savvy","description":"For discussion on being entrepreneurial and forging your business into an entity of global power. Learn marketing and negotiating tactics and how to push your product ideas into actual sales.","type":"f","ficon":"business-savvy.png"}]}}');
      break;
      case 380: jsonObj = JSON.parse('{"success":true,"message":"","result":{"name":"Crypto Currency","description":"For all discussion on crypto currency such as Bitcoin and Litecoin post here. Topics include mining, wallets, setup, monetization, and general digital currency talk.","type":"c","parent":241,"ficon":"snipta-f.png","children":[{"fid":379,"name":"Crypto Speculation and Investing","description":"Discuss investing, pricing, valuation, profits, and your crypto currency portfolio. Post about new ICO\'s and shoot for the moon.","type":"f","ficon":"speculationt.png"},{"fid":277,"name":"Coin Speak","description":"For all discussion on crypto currency topics that are not covered in other subforums. ","type":"f","ficon":"crypto-currency.png"},{"fid":377,"name":"Mining and Pools","description":"Discuss crypto currency mining and pools.  Learn how to get the most of your hardware and setup mining rigs.","type":"f","ficon":"mining..png"},{"fid":378,"name":"Wallets and Storage","description":"Discuss options for crypto currency wallets and safe coin storage. Learn how to do cold storage, use Trezor or Ledger Wallets, and even keep your transaction fees low.","type":"f","ficon":"wallets.png"}]}}');
      break;
      case 221: jsonObj = JSON.parse('{"success":true,"message":"","result":{"name":"Free Money Making Ebooks","description":"To give out free Money Making Guides please use this forum. Carefully read the rules for this section.  Enjoy making money online.","type":"f","parent":241,"ficon":"free-money-ebooks.png","children":[]}}');
      break;
      // 
      case 1: jsonObj = JSON.parse('');
      break;
      // Default so no crash
      default: jsonObj = JSON.parse('{"success":true,"message":"","result":{"name":"Rules,  Announcements, News, and Feedback","description":"This is where site rules and important announcements about the site are made. Please read carefully before you join. Also you can leave us feedback or ask site questions here.","type":"f","parent":1,"ficon":"rules-news-announcements.png","children":[{"fid":134,"name":"Suggestions and Ideas","description":"If you have a suggestion for HF please post it here. Note that many ideas have already been suggested so please take the time to read our stickies.","type":"f","ficon":"ideas-suggestions.png"},{"fid":162,"name":"HF News","description":"This is the HF News forum for weekly news editions. Check back here to find out about what\'s happening on Hack Forums every week. Thanks to Yin who founded this section and the HFNT, Writers who release the editions.","type":"f","ficon":"hf-news.png"},{"fid":140,"name":"Ub3r Support","description":"This is for ub3r support only.  No one but ub3r and staff have access to this section.","type":"f","ficon":"ub3r.png"}]}}');
      break;
    }
    if (jsonObj.success){
      return jsonObj.result;
    } else{
      console.log("get-forums failed to get data.");
    }
  }

}
