import { Injectable } from '@angular/core';
import 'rxjs/add/operator/map';


@Injectable()
export class GetCategoryProvider {

  constructor() {
    //console.log('Hello GetCategoryProvider Provider');
  }

  loadCategory(fid){
    // https://hackforums.net/api/v1/category/{fid}
    var jsonObj;
    console.log("FID: "+fid);
    switch(fid){
      case 1: jsonObj = JSON.parse('{"success":true,"message":"","result":{"name":"Hack Forums Official Information","description":"","type":"c","parent":0,"ficon":"shim.gif","children":[{"fid":2,"name":"Rules,  Announcements, News, and Feedback","description":"This is where site rules and important announcements about the site are made. Please read carefully before you join. Also you can leave us feedback or ask site questions here.","type":"f","ficon":"rules-news-announcements.png"}]}}');
      break;
      case 45: jsonObj = JSON.parse('{"success":true,"message":"","result":{"name":"Hacks, Exploits, and Various Discussions","description":"","type":"c","parent":0,"ficon":"shim.gif","children":[{"fid":4,"name":"Beginner Hacking","description":"This is for the entry level hacker wishing to learn more about the art of h4(k5.","type":"f","ficon":"beginner-hacking.png"},{"fid":307,"name":"Advanced Hacking","description":"If you feel you\'re past the beginner stages and want to delve deeper into computer security, analysis, and internet exploits you should participate here.","type":"c","ficon":"glider.png"},{"fid":10,"name":"Hacking Tools and Programs","description":"Since every hacker needs tools and programs please post your favorites here. ","type":"f","ficon":"keylogger2.png"},{"fid":43,"name":"Website and Forum Hacking","description":"We get a lot of discussions here about how to hack a website or  forum so this is the area for those threads.","type":"f","ficon":"website-hacking.png"},{"fid":47,"name":"Hacking Tutorials","description":"If you have a hacking tutorial please post it here for consideration to be in the Premium Hacking Tutorials.","type":"f","ficon":"hacker-tutorials.png"},{"fid":91,"name":"VPN, Proxies, and Socks","description":"For more advanced discussions on using and employing both proxies and socks please post here.  A proxy or VPN will help you stay anonymous on the internet.","type":"f","ficon":"proxies.png"},{"fid":104,"name":"Wifi WPA WEP Bluetooth 4G LTE Wireless Hacking","description":"For hacking wireless networks, wep\/wpa encryption, sniffers, setup, connection problems, aircrack and other wireless related discussions please join this forum. ","type":"f","ficon":"wifi.png"},{"fid":46,"name":"Skype, IRC, ICQ, AIM, XMPP, and IM Hacks","description":"If you are into exploiting instant messaging systems then we have a perfect forum for you. Post here for instant messenger hacks and exploits.","type":"f","ficon":"aim-msn-chat-hacking.png"},{"fid":193,"name":"Embedded Systems, Electronics, Gadgets, and DIY","description":"For all your hacking of electronics like radios, circuitry, alarms, radar detectors, cameras, remote controls or robots you can participate in this forum.  Great area for DIY projects. Topics include Raspberry Pi and Arduino.","type":"f","ficon":"gadgets.png"}]}}');
      break;
      case 7: jsonObj = JSON.parse('{"success":true,"message":"","result":{"name":"Hack Forums Open Discussion","description":"","type":"c","parent":0,"ficon":"shim.gif","children":[{"fid":25,"name":"The Lounge","description":"For great discussions on various subjects and to have some fun relaxed topics you can enter our Lounge.  Read the rules in the forums as trolling, spamming, or flaming are not allowed.","type":"f","ficon":"lounge.png"},{"fid":259,"name":"Personal Life","description":"Our personal life topics sections are all under subforums of this category.","type":"c","ficon":"personal-life.png"},{"fid":155,"name":"Member Contests","description":"This is a special forum dedicated to all the contests that members run. These are not official contests so participation is at your own risk.","type":"f","ficon":"contests.png"},{"fid":128,"name":"Science, Religion, Philosophy, and Politics","description":"Debates and other discussions that surround the topics of science, religion, politics and philosophy.  We ask all deep thinkers to post here.","type":"f","ficon":"science-religion.png"},{"fid":112,"name":"Anime Adventures","description":"Anime fans of HF rejoice for their special section. Topics include anime wallpapers,  anime art, how to draw anime, and anime movies.","type":"f","ficon":"anime.png"},{"fid":89,"name":"News and Happenings","description":"This is to discuss world news, local happenings, and interesting topics of what\'s going on in society.","type":"f","ficon":"world.png"},{"fid":37,"name":"Melody, Harmony, Rhythm, and MP3","description":"This is our music section. Listening with an iPod or your favorite MP3 player? Maybe you\'re a musician? Do you go to concerts?  We want all music threads here.","type":"f","ficon":"music.png"},{"fid":32,"name":"Movies, TV, and Videos","description":"This is our movies and video forum.  If you have something you wish to show us like a Youtube video or maybe discuss a new movie or TV show you have recently seen please post here.","type":"f","ficon":"cinema.png"}]}}');
      break;
      case 88: jsonObj = JSON.parse('{"success":true,"message":"","result":{"name":"Computing","description":"","type":"c","parent":0,"ficon":"shim.gif","children":[{"fid":110,"name":"White Hat Malware, Virus, and Rat Removal Help","description":"Wanna stop the Black Hats and Crackers?  Do you need assistance removing a RAT, virus, or malware?  Has your site been compromised?  Help others and get help here.","type":"f","ficon":"hat_white.png"},{"fid":87,"name":"Computer Overclocking, Customizing, and Hardware","description":"If you\'re building a system, overclocking your CPU\/GPU or just want to add something custom to your puter this is the right forum to discuss.","type":"f","ficon":"overclock.png"},{"fid":79,"name":"Smartphone, Mobiles, Apps, and SDK","description":"To discuss any mobile computing like iOS, Android, phreaking, app development, coding, tablets, troubleshooting or anything related to mobile we ask that you post them all here.","type":"f","ficon":"phreak.png"},{"fid":347,"name":"Windows 10","description":"Microsoft is rebooting with version 10 of their software. Most users will upgrade for free.  To discuss the Windows 10 OS please post here.","type":"f","ficon":"Windows10.png"},{"fid":85,"name":"Linux, FreeBSD, and Unix Flavors","description":"The popularity of the unix system built by AT&T in 1969 is still the basis for current operating systems.  Post about Linux, kernels, FreeBSD, and other topic in this forum.","type":"f","ficon":"unix_freebsd_linux.png"},{"fid":8,"name":"Miscellaneous Computer Talk","description":"For all computing posts not related to the other topics please post here.","type":"f","ficon":"computer_talk.png"},{"fid":159,"name":"Apple Mac and OS X","description":"For all Apple Mac family computers like the iMac, Macbook Air and Pro discussions.  Topics include OS X help, software assistance, and Mac network setup instructions.","type":"f","ficon":"apple.png"},{"fid":240,"name":"Networking, Routers, Switches, and Firewalls","description":"For assistance with networking we have this forum. Topics include router setup, firewall configurations, and advanced networking help such as Cisco routers.","type":"f","ficon":"networking.png"}]}}');
      break;
      case 151: jsonObj = JSON.parse('{"success":true,"message":"","result":{"name":"Programming, Coding, and Languages","description":"","type":"c","parent":0,"ficon":"shim.gif","children":[{"fid":5,"name":"Coding and Programming","description":"Ruby, ASP and other programming languages not covered in the other forums should be posted here.","type":"f","ficon":"hacker-coding.png"},{"fid":118,"name":"Visual Basic and .NET Framework","description":"Tutorials and coding help for Visual Basic are here. Microsoft\'s event driven language using the COM model. Also included are the .NET Framework topics. C# topics should be here too.","type":"f","ficon":"visual-basic.png"},{"fid":117,"name":"C\/C++\/Obj-C Programming","description":"A forum for the entire family of C\/C++\/Obj-C coding. Gain help on compiling, objects, classes, and functions.","type":"f","ficon":"cplusplus.png"},{"fid":154,"name":"PHP Development","description":"For PHP classes, functions, and development discussions we ask you post here. PHP is the #1 used web language and is easy to use. Its strength is its simplicity.","type":"f","ficon":"php-forum.png"},{"fid":49,"name":"Batch, Shell, Dos, and Command Line Interpreters","description":"For any hacker the base of their coding should be CLI.  The knowledge of the command line is crucial to being a legit hacker.","type":"f","ficon":"console.png"},{"fid":131,"name":"Java Language, JVM, and the JRE","description":"Write once and run anywhere.  That\'s Java. This is the forum for Oracle\'s popular language. Java is one of the best OOP languages available today. Learn more here.","type":"f","ficon":"java.png"},{"fid":129,"name":"Python","description":"Python is one of the most powerful adaptable general purpose languages.  We have this forum specifically devoted to the Python language.","type":"f","ficon":"python.png"},{"fid":375,"name":"HF API","description":"This is for development and coding of apps and software that utilize the HF API.","type":"f","ficon":"hfapi.png"}]}}');
      break;
      case 156: jsonObj = JSON.parse('{"success":true,"message":"","result":{"name":"Graphics","description":"","type":"c","parent":0,"ficon":"shim.gif","children":[{"fid":6,"name":"Graphics","description":"Not really anything to do with hacking but shit we have to show off some skillz somewhere.  Do it here.","type":"f","ficon":"graphics.png"},{"fid":133,"name":"Rate My Graphic","description":"These are threads related to graphic ratings such as your signature or avatar. Please make sure to make quality posts.","type":"f","ficon":"ratemygraphic.png"},{"fid":158,"name":"Free Graphic Requests ","description":"If you\'re in need of a signature or logo this is where you post.  Be sure to read any rules or stickies in this section before making a new thread.","type":"f","ficon":"gfx-requests.png"},{"fid":181,"name":"Free Graphic Services","description":"Offer free graphic services to members here. Free Graphic Services include such topics as signatures, website graphics, logos and member graphic shops.","type":"f","ficon":"graphic-services.png"},{"fid":220,"name":"Paid Graphic Work","description":"If you are offering commercial graphic services or maybe you are willing to pay for a graphic please click here. You will be redirected to the Graphics Market.","type":"f","ficon":"graphics-market.png"},{"fid":69,"name":"Graphic Tutorials","description":"Here are the tutorials for Photoshop, GIMP, Paint Shop Pro, and other graphical programs.","type":"f","ficon":"graphic_tutorials.png"},{"fid":160,"name":"Video Editing","description":"For discussions on creating and editing videos we have this forum. Topics include Youtube videos, video editing software tutorials, and programs like Avid or Sony Vegas.","type":"f","ficon":"video-editing.png"},{"fid":293,"name":"Photography 101","description":"Learn about digital and art photography in this forum. Topics include cameras, lenses, photo editing, great photographers, and your best pictures.","type":"f","ficon":"photography.png"}]}}');
      break;
      case 105: jsonObj = JSON.parse('{"success":true,"message":"","result":{"name":"Marketplace","description":"","type":"c","parent":0,"ficon":"shim.gif","children":[{"fid":163,"name":"Marketplace Discussions","description":"This is to be used for rules, policies, feedback, and general discussions about the HF Marketplace.  Please read the stickies in this section before conducting business here.","type":"f","ficon":"market-talk.png"},{"fid":107,"name":"Premium Sellers Section","description":"This area is only for upgraded member sales threads. ","type":"f","ficon":"premium-sellers.png"},{"fid":176,"name":"Secondary Sellers Market","description":"This is a sellers section open to all members.  We advise extreme caution in all deals here.  Sales threads must follow the policies of HF and we expect you to read them in the help documents.","type":"f","ficon":"selling.png"},{"fid":291,"name":"Online Accounts","description":"If you\'re selling an OG internet account this is your section. Top sellers include social networking accounts, popular IM names, and excellent email addresses.","type":"f","ficon":"accounts.png"},{"fid":136,"name":"Ebook Bazaar","description":"If you have an ebook for sale please post it here. All ebook sales should follow our template guidelines and rules.","type":"f","ficon":"ebook.png"},{"fid":44,"name":"Buyers Bay","description":"Are you looking for something?  Post your wanted ads in this area.  Examples would be games, downloads, or programs.  Be descriptive when creating threads.","type":"f","ficon":"wanted.png"},{"fid":225,"name":"Webmaster Marketplace","description":"If you\'re buying or selling hosting services, dedicated rentals, domains, and even websites then this is your forum.","type":"c","ficon":"webmaster-marketplace.png"},{"fid":106,"name":"Service Offerings","description":"If you would like to offer your services in exchange for payment please post in this section. Great place to offer graphic, web development, and coding services to our members.","type":"f","ficon":"services.png"},{"fid":308,"name":"Service Requests","description":"Here you can use our Marketplace to hire someone on HF for coding, graphics, security audits, or other internet work you need done.","type":"f","ficon":"service-requests.png"}]}}');
      break;
      case 241: jsonObj = JSON.parse('{"success":true,"message":"","result":{"name":"Making Money","description":"","type":"c","parent":0,"ficon":"shim.gif","children":[{"fid":120,"name":"Monetizing Techniques","description":"If you\'re looking for methods to make more money online this is your forum. We ask that if you have great ideas or a system to monetize please share it. Please read the rules for this forum.","type":"f","ficon":"monetizing.png"},{"fid":380,"name":"Crypto Currency","description":"For all discussion on crypto currency such as Bitcoin and Litecoin post here. Topics include mining, wallets, setup, monetization, and general digital currency talk.","type":"c","ficon":"snipta-f.png"},{"fid":221,"name":"Free Money Making Ebooks","description":"To give out free Money Making Guides please use this forum. Carefully read the rules for this section.  Enjoy making money online.","type":"f","ficon":"free-money-ebooks.png"},{"fid":127,"name":"Referrals","description":"If you want to promote something with a referral link it must be in this section only.","type":"f","ficon":"referral.gif"},{"fid":245,"name":"Survey Says","description":"For discussions on paid to complete, promotion of, and sharing of surveys this is your special money making forum. All money making survey talk belongs here.","type":"f","ficon":"survey-says.png"},{"fid":268,"name":"CPA \/ PPD Make Money","description":"For Cost Per Acquisition and Pay Per Download discussion we have added this forum. Earn more money from your online time.","type":"f","ficon":"cpappd.png"},{"fid":121,"name":"Shopping Deals","description":"Are you looking for that awesome discount or coupon?  Maybe you know about a deal you want to share. This area is for shopping deals both online and offline. ","type":"f","ficon":"shoppingdeals.png"},{"fid":281,"name":"Investment Strategies and Markets","description":"For discussions on stocks, bonds, forex, futures, IRA, 401k\'s, and other investment strategies.","type":"f","ficon":"markets.png"}]}}');
      break;
      case 141: jsonObj = JSON.parse('{"success":true,"message":"","result":{"name":"Webmasters","description":"","type":"c","parent":0,"ficon":"shim.gif","children":[{"fid":50,"name":"Website Construction","description":"This area is for discussions that involve aspects of site creation.  Including but not limited to PHP, CSS, XHTML, Javascript and even graphic design. ","type":"f","ficon":"website_construction.png"},{"fid":172,"name":"Website Showcase and Reviews","description":"This is where you can show off your website and ask for unbiased reviews.  Please read the sticky about what is not allowed here.  This is not meant for advertising of services.","type":"f","ficon":"website-showcase.png"},{"fid":142,"name":"SEO and Internet Marketing","description":"For those interested in making money from websites, social networking sites, and other internet marketing schemes please use this section.","type":"f","ficon":"blackhatseo.png"},{"fid":139,"name":"Social Networking","description":"If you want to discuss sites like Youtube, Facebook, or other social networking sites enter here.  Topics are not about hacking, spreading, or exploiting.  Read the rules.","type":"f","ficon":"blackhat-seo.png"},{"fid":143,"name":"Hosting","description":"This is for hosting discussions such as deals, comparisons, and troubleshooting. If you have the need or use a host make posts here.","type":"f","ficon":"webmaster-hosting.png"},{"fid":144,"name":"Web Servers and Dedicated Rentals","description":"If you need assistance with a web server or its services please post in this section.  Topics include Apache, MySQL, and MTA\'s.  Basically everything you need to run a successful server.","type":"f","ficon":"dedicatedservers.png"}]}}');
      break;
      case 80: jsonObj = JSON.parse('{"success":true,"message":"","result":{"name":"HF Gamers Zone","description":"","type":"c","parent":0,"ficon":"shim.gif","children":[{"fid":65,"name":"The Gamers Lounge","description":"For gaming enthusiast fans this is your group forum.","type":"f","ficon":"gamerslounge.png"},{"fid":14,"name":"Computer and Online Gaming","description":"For the PC gamers we have this forum area.  Online games like MMORPG\'s, FPS, or RTS video games as well as flash arcades can be talked about here.","type":"f","ficon":"gaming.png"},{"fid":82,"name":"Xbox 360, One, and Live Gaming","description":"The Microsoft Xbox is a fan favorite amongst online console gamers.  Xbox Live is a very strong gaming community.  ","type":"f","ficon":"xbox_360.png"},{"fid":179,"name":"Minecraft","description":"This retro feel java based game has gained popularity this past year. Its addictive gameplay and simple mechanics make it a hit. This is the Minecraft forums of HF.","type":"f","ficon":"minecraft.png"},{"fid":246,"name":"FPS and Military Style Gaming","description":"All of our popular military FPS game categories are subforums in this section.","type":"c","ficon":"fps.jpg"},{"fid":358,"name":"Pokemon Go","description":"Catch them all and discuss it here.  Did you find Pikachu yet? Share your best catches on HF. This game is crazy fun.","type":"f","ficon":"pokemon-go.jpg"},{"fid":81,"name":"Sony Gaming","description":"For all the PS4, PS3, PSN, PSP Vita, and PSP players in the HF community discuss your gaming addiction here. Playstation gamers get your butt in here.","type":"f","ficon":"ps3.png"},{"fid":212,"name":"Blizzard\'s Battle.net","description":"For all the Blizzard Battle.net games we\'ve created an organized category forum.  Discuss World of Warcraft, Starcraft, and Diablo here.","type":"c","ficon":"battlenet.png"},{"fid":237,"name":"Mobile and Tablet Gaming","description":"For those with Android, iPhone, Apps, Kindle Fire and Tablet gaming needs post here. Topics include Angry Birds, Fruit Ninja, and other popular mobile games.","type":"f","ficon":"mobile-games.png"},{"fid":290,"name":"Grand Theft Auto","description":"One of the most popular video games ever and it\'s a huge hit among HF members.  Discuss the game here and topics include GTA V, tutorials, screenshots, gameplay, and cheat codes.","type":"f","ficon":"gta.png"},{"fid":319,"name":"FIFA Game Forum","description":"For all things FIFA.  Discuss what is surely the greatest sports game in the world. The popular EA game continues to draw fans. Topics include the World Cup, FIFA Street, and FUT.","type":"f","ficon":"fifa.png"},{"fid":83,"name":"Nintendo Wii U and DS Systems","description":"This is a forum for the Nintendo fans which are plenty.  The new Wii U is released and the 3DS is just amazing.   Post here for Nintendo talk.","type":"f","ficon":"wii_ds.png"}]}}');
      break;
      case 53: jsonObj = JSON.parse('{"success":true,"message":"","result":{"name":"Crews and Clans Private Forums","description":"","type":"c","parent":0,"ficon":"crew_area.png","children":[{"fid":52,"name":"Group and Crew General Discussions","description":"For all topics regarding custom user groups such as recruitment, joining questions, and other threads about crews please post here.","type":"f","ficon":"crew_recruit.png"},{"fid":77,"name":"Harmony","description":"Harmony is a group that focuses on Music, Graphics, TV Shows\/Movies, photography, and everything else along those lines!","type":"f","ficon":"harmony-f.png"},{"fid":239,"name":"Skill","description":"From Atari to mobile, Skill is for gamers who simply love to game.","type":"f","ficon":"skill-f.png"},{"fid":381,"name":"Polyzen","description":"We\'re a group with many sides. Many objectives. Many purposes. But we have one core function: enhancing the community experience.","type":"f","ficon":"Polyzen-f.png"},{"fid":210,"name":"Writers","description":"This is the official subforums for the HF Writers. The only group allowed to edit the wiki. Group also responsible for HF News and assisting with Help Docs.","type":"f","ficon":"writers-ficon.png"}]}}');
      break;
    }
    if (jsonObj.success){
      return jsonObj.result.children;
    } else{
      console.log("get-forums failed to get data.");
    }
  }

}
